CREATE TABLE `post` (
  `id` bigint(20) unsigned NOT NULL,
  `blog_name` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '博主姓名',
  `post_url` tinytext COLLATE utf8mb4_unicode_ci COMMENT '网页地址',
  `slug` tinytext COLLATE utf8mb4_unicode_ci,
  `type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章类型',
  `timestamp` bigint(20) DEFAULT NULL COMMENT '时间戳',
  `date` datetime DEFAULT NULL,
  `state` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文章状态',
  `format` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文本格式',
  `reblog_key` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '转发 key',
  `tags` tinytext COLLATE utf8mb4_unicode_ci COMMENT '标签 序列化的数组',
  `short_url` tinytext COLLATE utf8mb4_unicode_ci COMMENT '短地址',
  `summary` tinytext COLLATE utf8mb4_unicode_ci COMMENT '摘要',
  `recommended_source` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  `recommended_color` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `highlighted` tinytext COLLATE utf8mb4_unicode_ci,
  `note_count` int(11) DEFAULT NULL COMMENT '评论数',
  `title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8mb4_unicode_ci,
  `photos` text COLLATE utf8mb4_unicode_ci COMMENT '照片资源',
  `image_permalink` tinytext COLLATE utf8mb4_unicode_ci,
  `caption` text COLLATE utf8mb4_unicode_ci,
  `reblog` text COLLATE utf8mb4_unicode_ci,
  `trail` text COLLATE utf8mb4_unicode_ci,
  `can_send_in_message` tinyint(1) DEFAULT NULL,
  `can_reply` tinyint(1) DEFAULT NULL,
  `video_url` tinytext COLLATE utf8mb4_unicode_ci COMMENT '视频地址',
  `html5_capable` tinyint(1) DEFAULT NULL COMMENT '是否支持 html5',
  `thumbnail_url` tinytext COLLATE utf8mb4_unicode_ci COMMENT '封面地址',
  `thumbnail_width` int(11) DEFAULT NULL COMMENT '封面图宽度',
  `thumbnail_height` int(11) DEFAULT NULL COMMENT '封面图高度',
  `duration` int(11) DEFAULT NULL COMMENT '视频时长',
  `player` text COLLATE utf8mb4_unicode_ci COMMENT '播放器代码',
  `video_type` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '视频类型: tumblr',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
